"""baseline schema

Revision ID: 42fd1a346122
Revises: 
Create Date: 2026-07-13 13:29:37.938582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fd1a346122'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('model_provider', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('extracted_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('reviewer_status', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('reviewer_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_extraction_case_id'), 'ai_extraction', ['case_id'], unique=False)
    op.create_table('app_user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('company_role', sa.String(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('approval_request',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requester_role', sa.String(), nullable=True),
    sa.Column('requester_name', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decider_role', sa.String(), nullable=True),
    sa.Column('decider_name', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.String(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_request_action_type'), 'approval_request', ['action_type'], unique=False)
    op.create_index(op.f('ix_approval_request_case_id'), 'approval_request', ['case_id'], unique=False)
    op.create_index(op.f('ix_approval_request_org_id'), 'approval_request', ['org_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    op.create_table('audit_finding',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('finding', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('auditor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('finding_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_case_id'), 'audit_log', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_log_org_id'), 'audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_table('audit_plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('lph_name', sa.String(), nullable=True),
    sa.Column('scheduled_date', sa.String(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('auditors', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_plan_case_id'), 'audit_plan', ['case_id'], unique=False)
    op.create_table('auditor_pool',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cert_no', sa.String(), nullable=True),
    sa.Column('role_in_team', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_application',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('nib', sa.String(), nullable=True),
    sa.Column('responsible_person', sa.String(), nullable=True),
    sa.Column('halal_supervisor', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('factory_reg_no', sa.String(), nullable=True),
    sa.Column('factory_address', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('notify_consent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('draft_state', sa.String(), nullable=True),
    sa.Column('return_reason', sa.Text(), nullable=True),
    sa.Column('pathway', sa.String(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=True),
    sa.Column('is_msme', sa.Boolean(), nullable=True),
    sa.Column('annual_revenue', sa.Integer(), nullable=True),
    sa.Column('outlet_count', sa.Integer(), nullable=True),
    sa.Column('sehati_eligible', sa.String(), nullable=True),
    sa.Column('fatwa_status', sa.String(), nullable=True),
    sa.Column('scope_frozen', sa.Boolean(), nullable=True),
    sa.Column('profile_ext', sa.JSON(), nullable=True),
    sa.Column('facility_ids', sa.JSON(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('change_impact',
    sa.Column('change_impact_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('required_actions', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('change_impact_id')
    )
    op.create_index(op.f('ix_change_impact_case_id'), 'change_impact', ['case_id'], unique=False)
    op.create_table('consultation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responder', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_org_id'), 'consultation', ['org_id'], unique=False)
    op.create_table('contract',
    sa.Column('contract_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('contract_no', sa.String(), nullable=True),
    sa.Column('party_a', sa.String(), nullable=True),
    sa.Column('effective_date', sa.String(), nullable=True),
    sa.Column('standard', sa.String(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('signatures', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    op.create_index(op.f('ix_contract_case_id'), 'contract', ['case_id'], unique=False)
    op.create_table('corrective_action',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewer_note', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_action_case_id'), 'corrective_action', ['case_id'], unique=False)
    op.create_index(op.f('ix_corrective_action_finding_id'), 'corrective_action', ['finding_id'], unique=False)
    op.create_table('deposit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('account_no_masked', sa.String(), nullable=True),
    sa.Column('depositor_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('ref_memo', sa.String(), nullable=True),
    sa.Column('deposit_at', sa.DateTime(), nullable=True),
    sa.Column('matched_invoice_id', sa.String(), nullable=True),
    sa.Column('match_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_matched_invoice_id'), 'deposit', ['matched_invoice_id'], unique=False)
    op.create_table('discussion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('author_role', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_asset',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=True),
    sa.Column('text_excerpt', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=True),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('content_b64', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('uploader_role', sa.String(), nullable=True),
    sa.Column('captured_at', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('external_identity',
    sa.Column('external_identity_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('external_username', sa.String(), nullable=True),
    sa.Column('external_email', sa.String(), nullable=True),
    sa.Column('external_application_no', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('identifier_match', sa.Boolean(), nullable=True),
    sa.Column('pathway', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('external_identity_id')
    )
    op.create_table('facility',
    sa.Column('facility_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('reg_no', sa.String(), nullable=True),
    sa.Column('profile_ext', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index(op.f('ix_facility_org_id'), 'facility', ['org_id'], unique=False)
    op.create_table('fatwa_decision',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_no', sa.String(), nullable=True),
    sa.Column('committee_note', sa.Text(), nullable=True),
    sa.Column('committee_head', sa.String(), nullable=True),
    sa.Column('committee_secretary', sa.String(), nullable=True),
    sa.Column('committee_members', sa.JSON(), nullable=True),
    sa.Column('product_scope', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('final_approved_at', sa.DateTime(), nullable=True),
    sa.Column('final_approver', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatwa_vote',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('member', sa.String(), nullable=False),
    sa.Column('vote', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fatwa_vote_case_id'), 'fatwa_vote', ['case_id'], unique=False)
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('feedback_comment',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_feedback_comment_feedback_id'), 'feedback_comment', ['feedback_id'], unique=False)
    op.create_table('feedback_image',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('content_b64', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_index(op.f('ix_feedback_image_feedback_id'), 'feedback_image', ['feedback_id'], unique=False)
    op.create_table('generated_document',
    sa.Column('gen_doc_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('gen_doc_id')
    )
    op.create_index(op.f('ix_generated_document_case_id'), 'generated_document', ['case_id'], unique=False)
    op.create_table('halal_certificate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('certificate_no', sa.String(), nullable=True),
    sa.Column('scope', sa.JSON(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('frozen_product_ids', sa.JSON(), nullable=True),
    sa.Column('frozen_material_ids', sa.JSON(), nullable=True),
    sa.Column('qr_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halal_certificate_qr_token'), 'halal_certificate', ['qr_token'], unique=False)
    op.create_table('hpas_evaluation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('element', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_ontology',
    sa.Column('ingredient_uid', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('e_number', sa.String(), nullable=True),
    sa.Column('default_status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('najis_risk', sa.Boolean(), nullable=True),
    sa.Column('carrier_check', sa.String(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('required_evidence', sa.JSON(), nullable=True),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_uid')
    )
    op.create_table('integration_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('request_hash', sa.String(), nullable=True),
    sa.Column('response_hash', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_event_case_id'), 'integration_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_integration_event_idempotency_key'), 'integration_event', ['idempotency_key'], unique=False)
    op.create_table('invoice',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('invoice_no', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('ppn', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('payment_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_invoice_payment_ref'), 'invoice', ['payment_ref'], unique=False)
    op.create_table('lph_assignment',
    sa.Column('lph_assignment_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('lph_name', sa.String(), nullable=True),
    sa.Column('auditor_ref', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lph_assignment_id')
    )
    op.create_table('lph_reference',
    sa.Column('lph_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('accreditation_no', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lph_id')
    )
    op.create_table('material',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('e_number', sa.String(), nullable=True),
    sa.Column('mat_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('cert', sa.String(), nullable=True),
    sa.Column('cert_no', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('v1_risk', sa.String(), nullable=True),
    sa.Column('evidence_provided', sa.Boolean(), nullable=True),
    sa.Column('source_known', sa.Boolean(), nullable=True),
    sa.Column('screen_result', sa.String(), nullable=True),
    sa.Column('screen_status', sa.String(), nullable=True),
    sa.Column('screen_severity', sa.String(), nullable=True),
    sa.Column('matched_uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('material_measurement',
    sa.Column('measurement_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=True),
    sa.Column('param_key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('tested_at', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('measurement_id')
    )
    op.create_index(op.f('ix_material_measurement_case_id'), 'material_measurement', ['case_id'], unique=False)
    op.create_index(op.f('ix_material_measurement_material_id'), 'material_measurement', ['material_id'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_org_id'), 'notification', ['org_id'], unique=False)
    op.create_table('onsite_checklist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org',
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('profile_ext', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('paid_by', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_case_id'), 'payment', ['case_id'], unique=False)
    op.create_index(op.f('ix_payment_invoice_id'), 'payment', ['invoice_id'], unique=False)
    op.create_table('payment_match_candidate',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('deposit_id', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.JSON(), nullable=True),
    sa.Column('decision_status', sa.String(), nullable=True),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_match_candidate_deposit_id'), 'payment_match_candidate', ['deposit_id'], unique=False)
    op.create_index(op.f('ix_payment_match_candidate_invoice_id'), 'payment_match_candidate', ['invoice_id'], unique=False)
    op.create_table('pendamping_assignment',
    sa.Column('assignment_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('pendamping_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('signature_ref', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('penyelia_halal',
    sa.Column('penyelia_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('training_cert', sa.String(), nullable=True),
    sa.Column('cert_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('penyelia_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('registration_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_org_id'), 'product', ['org_id'], unique=False)
    op.create_table('product_material',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decide_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_case_id'), 'refund', ['case_id'], unique=False)
    op.create_index(op.f('ix_refund_invoice_id'), 'refund', ['invoice_id'], unique=False)
    op.create_table('rule_version',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('effective_from', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('signature',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('signer', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('payload_hash', sa.String(), nullable=True),
    sa.Column('signature_value', sa.String(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_case_id'), 'signature', ['case_id'], unique=False)
    op.create_table('sjph_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('item_key', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('document_id', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_menu',
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('parent_menu_id', sa.String(), nullable=True),
    sa.Column('menu_code', sa.String(), nullable=True),
    sa.Column('menu_depth', sa.Integer(), nullable=True),
    sa.Column('menu_type', sa.String(), nullable=True),
    sa.Column('route_path', sa.String(), nullable=True),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.Column('permission_code', sa.String(), nullable=True),
    sa.Column('default_sort_order', sa.Integer(), nullable=True),
    sa.Column('use_yn', sa.Boolean(), nullable=True),
    sa.Column('required_yn', sa.Boolean(), nullable=True),
    sa.Column('system_admin_yn', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_sys_menu_menu_code'), 'sys_menu', ['menu_code'], unique=True)
    op.create_index(op.f('ix_sys_menu_parent_menu_id'), 'sys_menu', ['parent_menu_id'], unique=False)
    op.create_table('sys_menu_i18n',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('menu_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menu_i18n_menu_id'), 'sys_menu_i18n', ['menu_id'], unique=False)
    op.create_table('sys_menu_permission',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assignment_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_update', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('can_submit', sa.Boolean(), nullable=True),
    sa.Column('can_approve', sa.Boolean(), nullable=True),
    sa.Column('can_sign', sa.Boolean(), nullable=True),
    sa.Column('can_download', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_menu_permission_target_id'), 'sys_menu_permission', ['target_id'], unique=False)
    op.create_table('sys_org_menu',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('visible_yn', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_org_menu_org_id'), 'sys_org_menu', ['org_id'], unique=False)
    op.create_table('sys_role_menu',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('visible_yn', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_role_menu_role_id'), 'sys_role_menu', ['role_id'], unique=False)
    op.create_table('sys_user_menu',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('menu_id', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('visible_yn', sa.Boolean(), nullable=True),
    sa.Column('override_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_menu_user_id'), 'sys_user_menu', ['user_id'], unique=False)
    op.create_table('workflow_event',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(), nullable=True),
    sa.Column('row_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_event')
    op.drop_index(op.f('ix_sys_user_menu_user_id'), table_name='sys_user_menu')
    op.drop_table('sys_user_menu')
    op.drop_index(op.f('ix_sys_role_menu_role_id'), table_name='sys_role_menu')
    op.drop_table('sys_role_menu')
    op.drop_index(op.f('ix_sys_org_menu_org_id'), table_name='sys_org_menu')
    op.drop_table('sys_org_menu')
    op.drop_index(op.f('ix_sys_menu_permission_target_id'), table_name='sys_menu_permission')
    op.drop_table('sys_menu_permission')
    op.drop_index(op.f('ix_sys_menu_i18n_menu_id'), table_name='sys_menu_i18n')
    op.drop_table('sys_menu_i18n')
    op.drop_index(op.f('ix_sys_menu_parent_menu_id'), table_name='sys_menu')
    op.drop_index(op.f('ix_sys_menu_menu_code'), table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_table('sjph_evidence')
    op.drop_index(op.f('ix_signature_case_id'), table_name='signature')
    op.drop_table('signature')
    op.drop_table('rule_version')
    op.drop_index(op.f('ix_refund_invoice_id'), table_name='refund')
    op.drop_index(op.f('ix_refund_case_id'), table_name='refund')
    op.drop_table('refund')
    op.drop_table('product_material')
    op.drop_index(op.f('ix_product_org_id'), table_name='product')
    op.drop_table('product')
    op.drop_table('penyelia_halal')
    op.drop_table('pendamping_assignment')
    op.drop_index(op.f('ix_payment_match_candidate_invoice_id'), table_name='payment_match_candidate')
    op.drop_index(op.f('ix_payment_match_candidate_deposit_id'), table_name='payment_match_candidate')
    op.drop_table('payment_match_candidate')
    op.drop_index(op.f('ix_payment_invoice_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_case_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_table('org')
    op.drop_table('onsite_checklist')
    op.drop_index(op.f('ix_notification_org_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_material_measurement_material_id'), table_name='material_measurement')
    op.drop_index(op.f('ix_material_measurement_case_id'), table_name='material_measurement')
    op.drop_table('material_measurement')
    op.drop_table('material')
    op.drop_table('lph_reference')
    op.drop_table('lph_assignment')
    op.drop_index(op.f('ix_invoice_payment_ref'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_integration_event_idempotency_key'), table_name='integration_event')
    op.drop_index(op.f('ix_integration_event_case_id'), table_name='integration_event')
    op.drop_table('integration_event')
    op.drop_table('ingredient_ontology')
    op.drop_table('hpas_evaluation')
    op.drop_index(op.f('ix_halal_certificate_qr_token'), table_name='halal_certificate')
    op.drop_table('halal_certificate')
    op.drop_index(op.f('ix_generated_document_case_id'), table_name='generated_document')
    op.drop_table('generated_document')
    op.drop_index(op.f('ix_feedback_image_feedback_id'), table_name='feedback_image')
    op.drop_table('feedback_image')
    op.drop_index(op.f('ix_feedback_comment_feedback_id'), table_name='feedback_comment')
    op.drop_table('feedback_comment')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_fatwa_vote_case_id'), table_name='fatwa_vote')
    op.drop_table('fatwa_vote')
    op.drop_table('fatwa_decision')
    op.drop_index(op.f('ix_facility_org_id'), table_name='facility')
    op.drop_table('facility')
    op.drop_table('external_identity')
    op.drop_table('document_asset')
    op.drop_table('discussion')
    op.drop_index(op.f('ix_deposit_matched_invoice_id'), table_name='deposit')
    op.drop_table('deposit')
    op.drop_index(op.f('ix_corrective_action_finding_id'), table_name='corrective_action')
    op.drop_index(op.f('ix_corrective_action_case_id'), table_name='corrective_action')
    op.drop_table('corrective_action')
    op.drop_index(op.f('ix_contract_case_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_consultation_org_id'), table_name='consultation')
    op.drop_table('consultation')
    op.drop_index(op.f('ix_change_impact_case_id'), table_name='change_impact')
    op.drop_table('change_impact')
    op.drop_table('case_application')
    op.drop_table('auditor_pool')
    op.drop_index(op.f('ix_audit_plan_case_id'), table_name='audit_plan')
    op.drop_table('audit_plan')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_org_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_case_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('audit_finding')
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_org_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_case_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_action_type'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_ai_extraction_case_id'), table_name='ai_extraction')
    op.drop_table('ai_extraction')
    # ### end Alembic commands ###
